In [43]:
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
targets = np.array([[0],[0],[0],[1]])

In [44]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [1]:
class pcn_logic:
    
    def __init__(self):
        pass
    
    def train(self, inputs, targets, lr, n_iter):
        
        n_obs = np.shape(inputs)[0]
        n_in = np.shape(inputs)[1]
        n_out = np.shape(targets)[1]
        
        inputs = np.concatenate((inputs, - np.ones((n_obs,1))), axis = 1)
        
        weights = np.random.rand(n_in + 1,n_out)*0.1 - 0.05
        
        
        for i in range(n_iter):
            print('Iteration: {}\n'.format(i + 1))
            
            activation = np.where(np.dot(inputs, weights) > 0, 1, 0)
            
            print('Current Result\n{}\n'.format(activation))
            print('Target\n{}'.format(targets))
            print('-----------------------')
            
            if np.array_equal(activation,targets):
                break
            
            else:
                weights -= lr*np.dot(np.transpose(inputs),(activation - targets))
            
        self.weights = weights
        print('\npcn train completed')

In [2]:
pcn = pcn_logic()

In [71]:
pcn.train(inputs, targets, 0.25, 10)

Iteration: 1

Current Result
[[0]
 [0]
 [0]
 [0]]

Target
[[0]
 [0]
 [0]
 [1]]
-----------------------
Iteration: 2

Current Result
[[1]
 [1]
 [1]
 [1]]

Target
[[0]
 [0]
 [0]
 [1]]
-----------------------
Iteration: 3

Current Result
[[0]
 [0]
 [0]
 [0]]

Target
[[0]
 [0]
 [0]
 [1]]
-----------------------
Iteration: 4

Current Result
[[0]
 [0]
 [0]
 [1]]

Target
[[0]
 [0]
 [0]
 [1]]
-----------------------

pcn train completed


In [72]:
pcn.weights

array([[0.22066268],
       [0.24245701],
       [0.28647042]])